# Generated by Django 3.0.7 on 2020-06-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200626_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
